---
title: "Discounting"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse); library(data.table); library(broom); library(dtplyr); library(lme4); library(lmerTest); library(ggbeeswarm); library(cowplot)
rm(list = ls())
setwd("/Users/Hause/Dropbox/Working Projects/HL_DJW/Social_Media_Project/Discounting/")

# load("analysis_discounting.RData")
# save.image("analysis_discounting.RData")
source("/Users/Hause/Dropbox/Working Datasets/functionsR/helperFunctions.R")
```

```{r read data}
discountFacebook <- tbl_dt(fread("./Discounting Data/facebookdiscountraw_18_12_11.iqdat"))[, media := "facebook"]
discountInstagram <- tbl_dt(fread("./Discounting Data/instagramdiscountraw_18_12_11.iqdat"))[, media := "instagram"]
discountNetflix <- tbl_dt(fread("./Discounting Data/netflixdiscountraw_18_12_11.iqdat"))[, media := "netflix"]
```

```{r bind and clean data}
dt1 <- bind_rows(discountFacebook, discountInstagram, discountNetflix)

# rename variable names
(names(dt1) <- gsub(pattern = "values.", replacement = "", x = names(dt1))) 
dt1[, unique(trialnum)] # 6th (final) trial of each block is indifference point
dt2 <- dt1[trialnum == 6] %>% select(subject = group, delay = wordnumber, indifference = indiff, media) %>% arrange(subject, media, delay)

dt2[, indifferenceRelative := indifference / 100]

# exclude people who comppleted task multiple times
dt2[, .N, by = .(subject, media)] # should have 5 delays per media per person
toExclude <- dt2[, .N, by = .(subject, media)][N != 5, .(subject, media)] %>% distinct()
toExclude[, repeated := 1]

dt3 <- left_join(dt2, toExclude)
dt4 <- dt3[is.na(repeated)][, repeated := NULL]
dt4

dt4[, .N, by = .(subject, media)] # should have 5 delays per media per person
dt4[, .N, by = .(subject, media)][N != 5]
dt4[, .N, by = subject][, table(N)] # 5, 10, or 15

# which day is missing?
delays <- c(1, 3, 7, 14, 30, 90)
dt4[, missingDay := delays[which(!delays %in% delay)], by = .(subject, media)]

# write.csv(dt4, "discounting_indifference_points.csv", row.names = F)
```

```{r plot indifference}
grandavg_indiff <- seWithin(data = dt4, measurevar = "indifferenceRelative", withinvars = c("delay", "media"), idvar = "subject")

ggplot(grandavg_indiff, aes(delay, indifferenceRelative, col = media)) +
    # geom_quasirandom(data = dt4, alpha = 0.2, dodge = 1, size = 0.6) +
    geom_point(position = position_dodge(1), shape = 95, size = 6) +
    scale_x_continuous(breaks = unique(grandavg_indiff$delay)) +
    geom_errorbar(aes(ymin = indifferenceRelative - ci, ymax = indifferenceRelative + ci), position = position_dodge(1), width = 0, size = 1.1) +
    labs(x = "stopping media use for x days for some money", y = "subjective value")
```

```{r auc}
library(DescTools)
dt4[, auc := as.numeric(NA)]
dt4[delay %between% c(0, 100), auc := AUC(delay, indifference, method = "spline"), by = .(subject, media, missingDay)]
# dt4[delay %between% c(5, 80), auc := AUC(delay, indifference, method = "spline"), by = .(subject, media, missingDay)]
aucs <- dt4[, .(subject, media, auc, missingDay)] %>% distinct()
# write.csv(aucs, "discounting_aucs.csv", row.names = F)

dt4[subject %in% aucs[auc < 0, subject] & auc < 0] %>% print(n = 200)
```

```{r auc plot}
grandavg_auc <- seWithin(data = aucs[!missingDay %in% c(1, 90)], measurevar = "auc", withinvars = c("media"), idvar = "subject")

ggplot(grandavg_auc, aes(media, auc, col = media)) +
    # geom_quasirandom(data = aucs, alpha = 0.3, dodge = 1, size = 0.6) +
    geom_point(position = position_dodge(1), shape = 95, size = 6) +
    geom_errorbar(aes(ymin = auc - ci, ymax = auc + ci), position = position_dodge(1), width = 0, size = 1.1) +
    labs(x = "media", y = "discounting area-under-curve")
```

